Description: Create S3 bucket

Resources:

  BucketBeliscoS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-phtf-boto3
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True



