buckets:
  - name: bucket1phtf
    SSEAlgorithm: AES256
    BlockPublicAcls: True
    BlockPublicPolicy: True
    IgnorePublicAcls: True
    RestrictPublicBuckets: True

  - name: bucket2phtf
    SSEAlgorithm: AES256
    BlockPublicAcls: False
    BlockPublicPolicy: False
    IgnorePublicAcls: False
    RestrictPublicBuckets: False
