buckets:
  - name: bucket-1-phtf
    SSEAlgorithm: AES256
    BlockPublicAcls: True
    BlockPublicPolicy: True
    IgnorePublicAcls: True
    RestrictPublicBuckets: True

  - name: bucket-2-phtf
    SSEAlgorithm: AES256
    BlockPublicAcls: False
    BlockPublicPolicy: False
    IgnorePublicAcls: False
    RestrictPublicBuckets: False
